sudo: false
language: java
jdk: openjdk8
cache:
    apt: true
    directories:
        - $HOME/.m2
services:
    - xvfb
script: mvn clean verify -Pjacoco coveralls:report
notifications:
    slack: cunyponder:A8GuEoj0voEn2H7MJDL1eNji
