sudo: false
language: java
jdk: oraclejdk8
cache:
    apt: true
    directories:
        - $HOME/.m2
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: travis_wait 90 mvn install
notifications:
    slack: cunyponder:A8GuEoj0voEn2H7MJDL1eNji
